### ISSUE TITLE
gimme maps and automapper

### ISSUE THREAD

**Issue by ghost** [ClientPlayground/Dragon-Client#2]
he released new shit https://www.youtube.com/watch?v=LhUa_p_GuRM

also bruh moment (obfuscated with IIlllIIIIlI crap)

<img src="https://i.ibb.co/F6kgjSL/BRUHMOMENT.png" alt="BRUHMOMENT" border="0">

also it might be intent base... probably is idk  
too bored to look because sniping names rn :D

**Comment by itsnebulalol** [comment]
oh noOn Mon, Nov 8, 2021 at 7:17 PM Steve ***@***.***> wrote:
he released new shit https://www.youtube.com/watch?v=LhUa_p_GuRM

?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ghost** [comment]
oh no? more like oh yes because im pretty sure it uses the same mappings

**Comment by itsnebulalol** [comment]
lol they are stupidOn Tue, Nov 9, 2021 at 5:56 PM Steve ***@***.***> wrote:
oh no? more like oh yes because im pretty sure it uses the same mappings

?You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ghost** [comment]
So?

**Comment by ghost** [comment]
Hello!
These are the mappings: https://file.io/LVCmnX8mHvAX (Taken from MCP)
For the "automapper", you can search it up on youtube how to "deobfuscate" something with proguard using mappings
